//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.bbva.packws.webservice.solicitud;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListarSolicitudRequest complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ListarSolicitudRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.bbva.com.pe/pack-ws/}HeaderRequest"/>
 *         &lt;element name="body" type="{http://www.bbva.com.pe/pack-ws/}ListarSolicitudBodyRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListarSolicitudRequest", propOrder = {
        "header",
        "body"
})
public class ListarSolicitudRequest {

    @XmlElement(required = true)
    private HeaderRequest header;
    @XmlElement(required = true)
    private ListarSolicitudBodyRequest body;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is
     * {@link HeaderRequest }
     */
    public HeaderRequest getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is
     *              {@link HeaderRequest }
     */
    public void setHeader(HeaderRequest value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return possible object is
     * {@link ListarSolicitudBodyRequest }
     */
    public ListarSolicitudBodyRequest getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value allowed object is
     *              {@link ListarSolicitudBodyRequest }
     */
    public void setBody(ListarSolicitudBodyRequest value) {
        this.body = value;
    }

}
