//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

package com.bbva.packws.webservice.solicitud;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p/>
 * Java class for ListarSolicitudResponse complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ListarSolicitudResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.bbva.com.pe/pack-ws/}HeaderResponse"/>
 *         &lt;element name="body" type="{http://www.bbva.com.pe/pack-ws/}ListarSolicitudBodyResponse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListarSolicitudResponse", propOrder = {"header", "body"})
public class ListarSolicitudResponse {

    @XmlElement(required = true)
    private HeaderResponse header;
    private ListarSolicitudBodyResponse body;

    /**
     * Gets the value of the header property.
     *
     * @return possible object is {@link HeaderResponse }
     */
    public HeaderResponse getHeader() {
        if (header == null) {
            header = new HeaderResponse();
        }
        return header;
    }

    /**
     * Sets the value of the header property.
     *
     * @param value allowed object is {@link HeaderResponse }
     */
    public void setHeader(HeaderResponse value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     *
     * @return possible object is {@link ListarSolicitudBodyResponse }
     */
    public ListarSolicitudBodyResponse getBody() {
        if (body == null) {
            body = new ListarSolicitudBodyResponse();
        }
        return body;
    }

    /**
     * Sets the value of the body property.
     *
     * @param value allowed object is {@link ListarSolicitudBodyResponse }
     */
    public void setBody(ListarSolicitudBodyResponse value) {
        this.body = value;
    }

}
