//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.01 at 01:46:48 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bbva.com.pe/pack-ws/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bbva.packws.webservice.solicitud;
