spool 3_grants.log

GRANT SELECT ON IICE.TBL_EXPEDIENTE TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_CLIENTE TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_OFICINA TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_EMPLEADO TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_ESTADO TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_PRODUCTO TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_SUB_PRODUCTO TO CONELE WITH GRANT OPTION;
GRANT SELECT ON IICE.TBL_TIPO_DOCUMENTO_IDENTIDAD TO CONELE WITH GRANT OPTION;

spool off
