spool 3_grants.log

GRANT SELECT ON IICE.TBL_EXPEDIENTE TO CONELE;
GRANT SELECT ON IICE.TBL_CLIENTE TO CONELE;
GRANT SELECT ON IICE.TBL_OFICINA TO CONELE;
GRANT SELECT ON IICE.TBL_EMPLEADO TO CONELE;
GRANT SELECT ON IICE.TBL_ESTADO TO CONELE;
GRANT SELECT ON IICE.TBL_PRODUCTO TO CONELE;
GRANT SELECT ON IICE.TBL_SUB_PRODUCTO TO CONELE;
GRANT SELECT ON IICE.TBL_TIPO_DOCUMENTO_IDENTIDAD TO CONELE;
spool off
