spool 04_createView.log

CREATE OR REPLACE FUNCTION CONELE.SF_IS_NUMBER(VALOR VARCHAR2) RETURN NUMBER
AS
  RESULTADO NUMBER := NULL;
  TOTALCARACTERES INT;
BEGIN
  IF TRIM(VALOR) IS NOT NULL AND LENGTH(TRIM(VALOR)) > 0 THEN
    BEGIN
      TOTALCARACTERES := LENGTH ( TRIM ( TRANSLATE ( VALOR, ' +-.0123456789', ' ' ) ) );
      IF TOTALCARACTERES IS NULL THEN
        RESULTADO := TO_NUMBER(VALOR);
      END IF;
    EXCEPTION
    WHEN OTHERS THEN
      RESULTADO := NULL;
    END;
  END IF;

  RETURN RESULTADO;
END SF_IS_NUMBER;

CREATE OR REPLACE VIEW CONELE.V_SOLICITUD AS
SELECT EXP.ID AS SOLICITUD
  , PRO.CODIGO AS CODIGO_PRODUCTO
  , SPR.CODIGO AS CODIGO_SUBPRODUCTO
  , EST.CODIGO AS ESTADO
  , EXP.FEC_REGISTRO AS FECHA_ALTA
  , ETC.LINEA_CRED_SOL AS IMPORTE
  , ETC.ID_TIPMONSOL_FK AS DIVISA
  , DOC.CODIGO AS TIPO_DOI
  , CLI.NUM_DOI AS NUM_DOI
  , CLI.COD_CLIENTE AS CODIGO_CLIENTE
  , ETC.NRO_CONTRATO AS CONTRATO
  , CONELE.SF_IS_NUMBER(ETC.PLAZO_SOL) AS PLAZO
  , OFI.CODIGO AS OFICINA
  , ETC.ID_OFICINA_FK AS OFICINA_CODIGO
  , EMP.CODIGO AS EJECUTIVO
  , EXP.ID_EMPLEADO_FK AS EJECUTIVO_CODIGO
  , ETC.TASA_ESP AS TASA
  , HEST.CODIGO AS ESTADO_PACK
  , HDOC.CODIGO AS TIPODOCUMENTO_PACK
  , HPRO.CODIGO AS PRODUCTO_PACK
  , HSPR.CODIGO AS SUBPRODUCTO_PACK
FROM CONELE.TBL_CE_IBM_EXPEDIENTE EXP
  INNER JOIN CONELE.TBL_CE_IBM_EXPEDIENTE_TC ETC ON EXP.ID = ETC.ID_EXP_FK
  INNER JOIN CONELE.TBL_CE_IBM_CLIENTE_NATURAL CLI ON CLI.ID = EXP.ID_CLIENTE_NATURAL_FK
  INNER JOIN CONELE.TBL_CE_IBM_PRODUCTO PRO ON EXP.ID_PRODUCTO_FK = PRO.ID
  INNER JOIN CONELE.TBL_CE_IBM_ESTADO EST ON EXP.ID_ESTADO_FK = EST.ID
  INNER JOIN CONELE.TBL_CE_IBM_SUBPRODUCTO SPR ON ETC.ID_SUBPRODUCTO_FK = SPR.ID
  INNER JOIN CONELE.TBL_CE_IBM_TIPO_DOI DOC ON CLI.ID_TIPO_DOI_FK = DOC.ID
  LEFT JOIN CONELE.TBL_CE_IBM_OFICINA OFI ON ETC.ID_OFICINA_FK = OFI.ID
  LEFT JOIN CONELE.TBL_CE_IBM_EMPLEADO EMP ON EXP.ID_EMPLEADO_FK = EMP.ID
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HEST ON EST.CODIGO = HEST.ENTERO AND HEST.ID_PARAMETRIA=1
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HDOC ON DOC.CODIGO = HDOC.ENTERO AND HDOC.ID_PARAMETRIA=2
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HPRO ON PRO.CODIGO = HPRO.ENTERO AND HPRO.ID_PARAMETRIA=3
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HSPR ON SPR.CODIGO = HSPR.ENTERO AND HSPR.ID_PARAMETRIA=4
ORDER BY EXP.ID;

CREATE OR REPLACE VIEW CONELE.V_SOLICITUD_IICE AS
SELECT A.SOLICITUD
  , A.CODIGO_PRODUCTO
  , A.CODIGO_SUBPRODUCTO
  , A.ESTADO
  , A.FECHA_ALTA
  , A.IMPORTE
  , A.DIVISA
  , A.TIPO_DOI
  , A.NUM_DOI
  , A.CODIGO_CLIENTE
  , A.CONTRATO
  , A.PLAZO
  , A.OFICINA
  , A.OFICINA_CODIGO
  , A.EJECUTIVO
  , A.EJECUTIVO_CODIGO
  , A.TASA
  , HEST.CODIGO AS ESTADO_PACK
  , HDOC.CODIGO AS TIPODOCUMENTO_PACK
  , HPRO.CODIGO AS PRODUCTO_PACK
  , HSPR.CODIGO AS SUBPRODUCTO_PACK  
FROM (
  SELECT EXP.CORRELATIVO_EXPEDIENTE AS SOLICITUD
    , PRO.CODIGO AS CODIGO_PRODUCTO
    , EXP.CORRELATIVO_SUB_PRODUCTO AS CODIGO_SUBPRODUCTO
    , EST.CODIGO AS ESTADO
    , EXP.FECHA_CREACION AS FECHA_ALTA
    , EXP.IMPORTE_SOLICITADO_PRESTAMO AS IMPORTE
    , EXP.CORRELATIVO_MONEDA AS DIVISA
    , CLI.CORRELATIVO_TIPO_DOC_IDENTIDAD AS TIPO_DOI
    , CLI.DOI AS NUM_DOI
    , CLI.CODIGO AS CODIGO_CLIENTE
    , REPLACE(EXP.CODIGO_CONTRATO, '-', '') AS CONTRATO
    , EXP.PLAZO_SOLICITADO AS PLAZO
    , OFI.CODIGO AS OFICINA
    , EXP.CORRELATIVO_OFICINA AS OFICINA_CODIGO
    , EMP.CODIGO AS EJECUTIVO
    , EXP.CODIGO_USUARIO_CREACION AS EJECUTIVO_CODIGO
    , EXP.TASA_ESPECIAL AS TASA
  FROM IICE.TBL_EXPEDIENTE@ORABBVA@IICE EXP
    INNER JOIN IICE.TBL_CLIENTE@ORABBVA@IICE CLI ON CLI.CORRELATIVO_CLIENTE = EXP.CORRELATIVO_CLIENTE
    INNER JOIN IICE.TBL_ESTADO@ORABBVA@IICE EST ON EXP.CORRELATIVO_ESTADO = EST.CORRELATIVO_ESTADO
    INNER JOIN IICE.TBL_PRODUCTO@ORABBVA@IICE PRO ON EXP.CORRELATIVO_PRODUCTO = PRO.CORRELATIVO_PRODUCTO
    LEFT JOIN IICE.TBL_OFICINA@ORABBVA@IICE OFI ON EXP.CORRELATIVO_OFICINA = OFI.CORRELATIVO_OFICINA
    LEFT JOIN IICE.TBL_EMPLEADO@ORABBVA@IICE EMP ON EXP.CODIGO_USUARIO_CREACION = EMP.CODIGO
  ) A 
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HEST ON A.ESTADO = HEST.TEXTO AND HEST.ID_PARAMETRIA=1
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HDOC ON A.TIPO_DOI = HDOC.TEXTO AND HDOC.ID_PARAMETRIA=2
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HPRO ON A.CODIGO_PRODUCTO = HPRO.TEXTO AND HPRO.ID_PARAMETRIA=3
  LEFT JOIN CONELE.TBL_CE_IBM_MULTITABLA HSPR ON A.CODIGO_SUBPRODUCTO = HSPR.TEXTO AND HSPR.ID_PARAMETRIA=4
ORDER BY A.SOLICITUD;
 
spool off
