spool 08_updateBlob_READER_XML_WSDL.log

DECLARE
  TMP_BLOB BLOB := EMPTY_BLOB();
  SRC_CHUNK_01 RAW(32767);
  SRC_CHUNK_02 RAW(32767);
  SRC_CHUNK_03 RAW(32767);
  SRC_CHUNK_04 RAW(32767);
  SRC_CHUNK_05 RAW(32767);
  SRC_CHUNK_06 RAW(32767);
  SRC_CHUNK_07 RAW(32767);
  SRC_CHUNK_08 RAW(32767);
  SRC_CHUNK_09 RAW(32767);
  SRC_CHUNK_10 RAW(32767);
  SRC_CHUNK_11 RAW(32767);
  SRC_CHUNK_12 RAW(32767);
  SRC_CHUNK_13 RAW(32767);
  SRC_CHUNK_14 RAW(32767);
  SRC_CHUNK_15 RAW(32767);
  SRC_CHUNK_16 RAW(32767);
  SRC_CHUNK_17 RAW(32767);
  SRC_CHUNK_18 RAW(32767);
  SRC_CHUNK_19 RAW(32767);
  SRC_CHUNK_20 RAW(32767);
  SRC_CHUNK_22 RAW(32767);
  SRC_CHUNK_23 RAW(32767);
  SRC_CHUNK_24 RAW(32767);
  SRC_CHUNK_25 RAW(32767);
  SRC_CHUNK_26 RAW(32767);
  LEN_CHUNK BINARY_INTEGER;
BEGIN
  SRC_CHUNK_01 := UTL_RAW.CAST_TO_RAW('{"class":"com.everis.webservice.WSDLResource","elements":{"obtenerTerritorioRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerTerritorioRequest","ref":null,"type":null,"value":null},"listarOficinaRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaRequest","ref":null,"type":null,"value":null},"Oficina":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreOficina","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"territorio","ref":null,"type":"Territorio","value":n');
  SRC_CHUNK_02 := UTL_RAW.CAST_TO_RAW('ull},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficinaMadre","ref":null,"type":"OficinaMadre","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficinasHijas","ref":null,"type":"OficinaHija","value":null}],"class":"com.everis.webservice.WSDLElement","name":"Oficina","ref":null,"type":null,"value":null},"listarOficinaTerritorioRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"term","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioRequest","ref":null,"type":null,"value":null},"obtenerOficinaResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement",');
  SRC_CHUNK_03 := UTL_RAW.CAST_TO_RAW('"name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerOficinaResponse","ref":null,"type":null,"value":null},"listarAreaResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaArea","ref":null,"type":"Suprarea","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarAreaResponse","ref":null,"type":null,"value":null},"listarTerritorioRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codArea","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDL');
  SRC_CHUNK_04 := UTL_RAW.CAST_TO_RAW('Element","name":"listarTerritorioRequest","ref":null,"type":null,"value":null},"listarTerritorioResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaTerritorio","ref":null,"type":"Territorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarTerritorioResponse","ref":null,"type":null,"value":null},"listarOficinaTerritorioSuprareaRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"term","ref":null,"type":"string","value":"%"}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioSuprareaRequest","ref":null,"type":null,"value":null},"listarAreaRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLE');
  SRC_CHUNK_05 := UTL_RAW.CAST_TO_RAW('lement","name":"codBanca","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarAreaRequest","ref":null,"type":null,"value":null},"OficinaMadre":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreOficina","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"OficinaMadre","ref":null,"type":null,"value":null},"Territorio":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreTerritorio","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"suprarea","ref":null,"type":"Suprarea","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement"');
  SRC_CHUNK_06 := UTL_RAW.CAST_TO_RAW(',"name":"oficinas","ref":null,"type":"OficinaTerritorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"Territorio","ref":null,"type":null,"value":null},"OficinaHija":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreOficina","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficinaMadre","ref":null,"type":"OficinaMadre","value":null}],"class":"com.everis.webservice.WSDLElement","name":"OficinaHija","ref":null,"type":null,"value":null},"Banca":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreSuprarea","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"Banca","ref');
  SRC_CHUNK_07 := UTL_RAW.CAST_TO_RAW('":null,"type":null,"value":null},"obtenerTerritorioResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"territorio","ref":null,"type":"Territorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerTerritorioResponse","ref":null,"type":null,"value":null},"Suprarea":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreSuprarea","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"suprarea","ref":null,"type":"Banca","value":null}],"class":"com.everis.webservice.WSDLElement","name":"');
  SRC_CHUNK_08 := UTL_RAW.CAST_TO_RAW('Suprarea","ref":null,"type":null,"value":null},"listarOficinaResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaResponse","ref":null,"type":null,"value":null},"obtenerOficinaRequest":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codOficina","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerOficinaRequest","ref":null,"type":null,"value":null},"listarOficinaTerritorioSuprareaResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":');
  SRC_CHUNK_09 := UTL_RAW.CAST_TO_RAW('"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioSuprareaResponse","ref":null,"type":null,"value":null},"listarOficinaTerritorioResponse":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioResponse","ref":null,"type":null,"value":null},"OficinaTerritorio":{"attributes":[{"attributes":[],"class":"c');
  SRC_CHUNK_10 := UTL_RAW.CAST_TO_RAW('om.everis.webservice.WSDLElement","name":"id","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"nombreOficina","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficinaMadre","ref":null,"type":"OficinaMadre","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"idTerritorio","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficinasHijas","ref":null,"type":"OficinaHija","value":null}],"class":"com.everis.webservice.WSDLElement","name":"OficinaTerritorio","ref":null,"type":null,"value":null}},"messages":{"obtenerTerritorio":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerTerritor');
  SRC_CHUNK_11 := UTL_RAW.CAST_TO_RAW('ioRequest","ref":null,"type":null,"value":null},"name":"obtenerTerritorio","part":null},"obtenerOficinaResponse":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerOficinaResponse","ref":null,"type":null,"value":null},"name":"obtenerOficinaResponse","part":null},"listarAreaResponse":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","');
  SRC_CHUNK_12 := UTL_RAW.CAST_TO_RAW('ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaArea","ref":null,"type":"Suprarea","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarAreaResponse","ref":null,"type":null,"value":null},"name":"listarAreaResponse","part":null},"listarTerritorioResponse":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaTerritorio","ref":null,"type":"Territorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarTerritorioResponse","ref":null,"type":null,"value":null},"name":"listarTerritorioResponse","part":null},"listarArea":{"class":"com.everis.webservice.WSDLMes');
  SRC_CHUNK_13 := UTL_RAW.CAST_TO_RAW('sage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codBanca","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarAreaRequest","ref":null,"type":null,"value":null},"name":"listarArea","part":null},"obtenerOficina":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codOficina","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerOficinaRequest","ref":null,"type":null,"value":null},"name":"obtenerOficina","part":null},"obtenerTerritorioResponse":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attri');
  SRC_CHUNK_14 := UTL_RAW.CAST_TO_RAW('butes":[],"class":"com.everis.webservice.WSDLElement","name":"territorio","ref":null,"type":"Territorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerTerritorioResponse","ref":null,"type":null,"value":null},"name":"obtenerTerritorioResponse","part":null},"listarOficinaResponse":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaResponse","ref":null,"type":null,"value":null},"name":"listarOficinaResponse","part":null},"listarOficinaTerritorioSuprareaResponse":{"class":"com.everis.webservice.WSDLMessage","element":');
  SRC_CHUNK_15 := UTL_RAW.CAST_TO_RAW('{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioSuprareaResponse","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorioSuprareaResponse","part":null},"listarTerritorio":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codArea","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarTerritorioRequest","ref":null,"type":null,"value":null},"name":"listarTerritorio","part":null},"listarOficinaTerritorio":{"class":"com.everis.webservice.WSDL');
  SRC_CHUNK_16 := UTL_RAW.CAST_TO_RAW('Message","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"term","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioRequest","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorio","part":null},"listarOficina":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaRequest","ref":null,"type":null,"value":null},"name":"listarOficina","part":null},"listarOficinaTerritorioSuprarea":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"term","ref":null,"type":"s');
  SRC_CHUNK_17 := UTL_RAW.CAST_TO_RAW('tring","value":"%"}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioSuprareaRequest","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorioSuprarea","part":null},"listarOficinaTerritorioResponse":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioResponse","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorioResponse","part":null}},"operations":{"obtenerTerritorio":{"class":"com.everis.webservice.WSDLOperation","input":{"class":"com.everis.webservice.WSDLMessage","element":{"');
  SRC_CHUNK_18 := UTL_RAW.CAST_TO_RAW('attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerTerritorioRequest","ref":null,"type":null,"value":null},"name":"obtenerTerritorio","part":null},"name":"obtenerTerritorio","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"territorio","ref":null,"type":"Territorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerTerritorioResponse","ref":null,"type":null,"value":null},"name":"obtenerTerritorioResponse","part":null}},"obtenerOficina":{"class":"com.everis.webservice.WSDLOperation","');
  SRC_CHUNK_19 := UTL_RAW.CAST_TO_RAW('input":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codOficina","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerOficinaRequest","ref":null,"type":null,"value":null},"name":"obtenerOficina","part":null},"name":"obtenerOficina","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"oficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"obtenerOficinaResponse","ref":null,"type":null,"value":null},"name":"obtenerOficinaResponse","part":null}},"listarTerritorio":{"clas');
  SRC_CHUNK_20 := UTL_RAW.CAST_TO_RAW('s":"com.everis.webservice.WSDLOperation","input":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codArea","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarTerritorioRequest","ref":null,"type":null,"value":null},"name":"listarTerritorio","part":null},"name":"listarTerritorio","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaTerritorio","ref":null,"type":"Territorio","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarTerritorioResponse","ref":null,"type":null,"value":null},"name":"lista');
  SRC_CHUNK_22 := UTL_RAW.CAST_TO_RAW('rTerritorioResponse","part":null}},"listarOficinaTerritorio":{"class":"com.everis.webservice.WSDLOperation","input":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"term","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioRequest","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorio","part":null},"name":"listarOficinaTerritorio","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WS');
  SRC_CHUNK_23 := UTL_RAW.CAST_TO_RAW('DLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioResponse","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorioResponse","part":null}},"listarOficina":{"class":"com.everis.webservice.WSDLOperation","input":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codTerritorio","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaRequest","ref":null,"type":null,"value":null},"name":"listarOficina","part":null},"name":"listarOficina","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","v');
  SRC_CHUNK_24 := UTL_RAW.CAST_TO_RAW('alue":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaResponse","ref":null,"type":null,"value":null},"name":"listarOficinaResponse","part":null}},"listarOficinaTerritorioSuprarea":{"class":"com.everis.webservice.WSDLOperation","input":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"term","ref":null,"type":"string","value":"%"}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioSuprareaRequest","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorioSuprarea","part":null},"name":"listarOficinaTerritorioSuprarea","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"tipoResultado","ref":null,"type":"string","value":null},{"a');
  SRC_CHUNK_25 := UTL_RAW.CAST_TO_RAW('ttributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaOficina","ref":null,"type":"Oficina","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarOficinaTerritorioSuprareaResponse","ref":null,"type":null,"value":null},"name":"listarOficinaTerritorioSuprareaResponse","part":null}},"listarArea":{"class":"com.everis.webservice.WSDLOperation","input":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"codBanca","ref":null,"type":"string","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarAreaRequest","ref":null,"type":null,"value":null},"name":"listarArea","part":null},"name":"listarArea","output":{"class":"com.everis.webservice.WSDLMessage","element":{"attributes":[{"attributes":[],"class":"com.everis.webservice.WSDLElement","name"');
  SRC_CHUNK_26 := UTL_RAW.CAST_TO_RAW(':"tipoResultado","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"mensaje","ref":null,"type":"string","value":null},{"attributes":[],"class":"com.everis.webservice.WSDLElement","name":"listaArea","ref":null,"type":"Suprarea","value":null}],"class":"com.everis.webservice.WSDLElement","name":"listarAreaResponse","ref":null,"type":null,"value":null},"name":"listarAreaResponse","part":null}}},"targetNamespace":"http://www.bbva.com.pe/CentrosBBVAWebService/","url":"http://118.180.34.16/CentrosBBVAWS/CentrosBBVAWebService?wsdl"');

  UPDATE CONELE.MNTR_PARAMETRO SET BINARIO = EMPTY_BLOB() WHERE ID = 8;

  SELECT BINARIO INTO TMP_BLOB
  FROM CONELE.MNTR_PARAMETRO
  WHERE ID = 8 FOR UPDATE;
  
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_01), SRC_CHUNK_01);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_02), SRC_CHUNK_02);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_03), SRC_CHUNK_03);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_04), SRC_CHUNK_04);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_05), SRC_CHUNK_05);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_06), SRC_CHUNK_06);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_07), SRC_CHUNK_07);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_08), SRC_CHUNK_08);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_09), SRC_CHUNK_09);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_10), SRC_CHUNK_10);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_11), SRC_CHUNK_11);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_12), SRC_CHUNK_12);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_13), SRC_CHUNK_13);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_14), SRC_CHUNK_14);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_15), SRC_CHUNK_15);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_16), SRC_CHUNK_16);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_17), SRC_CHUNK_17);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_18), SRC_CHUNK_18);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_19), SRC_CHUNK_19);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_20), SRC_CHUNK_20);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_22), SRC_CHUNK_22);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_23), SRC_CHUNK_23);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_24), SRC_CHUNK_24);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_25), SRC_CHUNK_25);
  DBMS_LOB.WRITEAPPEND(TMP_BLOB, UTL_RAW.LENGTH(SRC_CHUNK_26), SRC_CHUNK_26);

  UPDATE CONELE.MNTR_PARAMETRO
  SET 
    BINARIO = (SELECT BINARIO FROM CONELE.MNTR_PARAMETRO WHERE ID = 8)
  WHERE ID = 3;
  
  COMMIT;
END;
/

spool off