TRUNCATE TABLE CONELE.BATCH_STEP_EXECUTION_CONTEXT;
DELETE FROM CONELE.BATCH_STEP_EXECUTION;
DELETE FROM CONELE.BATCH_JOB_EXECUTION_PARAMS;
DELETE FROM CONELE.BATCH_JOB_EXECUTION_CONTEXT;
DELETE FROM CONELE.BATCH_JOB_EXECUTION;
DELETE FROM CONELE.BATCH_JOB_INSTANCE;
COMMIT;
