spool 2_createObjectsQUARTZ.log

CREATE TABLE CONELE.QRTZ_JOB_DETAILS (
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    JOB_CLASS_NAME   VARCHAR2(250) NOT NULL, 
    IS_DURABLE VARCHAR2(1) NOT NULL,
    IS_VOLATILE VARCHAR2(1) NOT NULL,
    IS_STATEFUL VARCHAR2(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (JOB_NAME,JOB_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_JOB_LISTENERS (
    JOB_NAME  VARCHAR2(200) NOT NULL, 
    JOB_GROUP VARCHAR2(200) NOT NULL,
    JOB_LISTENER VARCHAR2(200) NOT NULL,
    PRIMARY KEY (JOB_NAME,JOB_GROUP,JOB_LISTENER),
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
    REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_TRIGGERS (
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL, 
    JOB_GROUP VARCHAR2(200) NOT NULL,
    IS_VOLATILE VARCHAR2(1) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    NEXT_FIRE_TIME NUMBER(13) NULL,
    PREV_FIRE_TIME NUMBER(13) NULL,
    PRIORITY NUMBER(13) NULL,
    TRIGGER_STATE VARCHAR2(16) NOT NULL,
    TRIGGER_TYPE VARCHAR2(8) NOT NULL,
    START_TIME NUMBER(13) NOT NULL,
    END_TIME NUMBER(13) NULL,
    CALENDAR_NAME VARCHAR2(200) NULL,
    MISFIRE_INSTR NUMBER(2) NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
    REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP) 
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_SIMPLE_TRIGGERS (
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    REPEAT_COUNT NUMBER(7) NOT NULL,
    REPEAT_INTERVAL NUMBER(12) NOT NULL,
    TIMES_TRIGGERED NUMBER(10) NOT NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_CRON_TRIGGERS (
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    TIME_ZONE_ID VARCHAR2(80),
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_BLOB_TRIGGERS (
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_TRIGGER_LISTENERS (
    TRIGGER_NAME  VARCHAR2(200) NOT NULL, 
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    TRIGGER_LISTENER VARCHAR2(200) NOT NULL,
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_LISTENER),
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE QRTZ_CALENDARS
  (
    CALENDAR_NAME  VARCHAR2(200) NOT NULL, 
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (CALENDAR_NAME)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_PAUSED_TRIGGER_GRPS (
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL, 
    PRIMARY KEY (TRIGGER_GROUP)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_FIRED_TRIGGERS (
    ENTRY_ID VARCHAR2(95) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    IS_VOLATILE VARCHAR2(1) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    FIRED_TIME NUMBER(13) NOT NULL,
    PRIORITY NUMBER(13) NOT NULL,
    STATE VARCHAR2(16) NOT NULL,
    JOB_NAME VARCHAR2(200) NULL,
    JOB_GROUP VARCHAR2(200) NULL,
    IS_STATEFUL VARCHAR2(1) NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NULL,
    PRIMARY KEY (ENTRY_ID)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_SCHEDULER_STATE (
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13) NOT NULL,
    CHECKIN_INTERVAL NUMBER(13) NOT NULL,
    PRIMARY KEY (INSTANCE_NAME)
)TABLESPACE CONELE_DAT;

CREATE TABLE CONELE.QRTZ_LOCKS (
    LOCK_NAME  VARCHAR2(40) NOT NULL, 
    PRIMARY KEY (LOCK_NAME)
)TABLESPACE CONELE_DAT;

CREATE INDEX CONELE.IDX_QRTZ_J_REQ_RECOVERY      ON CONELE.QRTZ_JOB_DETAILS(REQUESTS_RECOVERY) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_T_NEXT_FIRE_TIME    ON CONELE.QRTZ_TRIGGERS(NEXT_FIRE_TIME) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_T_STATE             ON CONELE.QRTZ_TRIGGERS(TRIGGER_STATE) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_T_NFT_ST            ON CONELE.QRTZ_TRIGGERS(NEXT_FIRE_TIME,TRIGGER_STATE) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_T_VOLATILE          ON CONELE.QRTZ_TRIGGERS(IS_VOLATILE) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_TRIG_NAME        ON CONELE.QRTZ_FIRED_TRIGGERS(TRIGGER_NAME) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_TRIG_GROUP       ON CONELE.QRTZ_FIRED_TRIGGERS(TRIGGER_GROUP) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_TRIG_NM_GP       ON CONELE.QRTZ_FIRED_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_TRIG_VOLATILE    ON CONELE.QRTZ_FIRED_TRIGGERS(IS_VOLATILE) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_TRIG_INST_NAME   ON CONELE.QRTZ_FIRED_TRIGGERS(INSTANCE_NAME) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_JOB_NAME         ON CONELE.QRTZ_FIRED_TRIGGERS(JOB_NAME) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_JOB_GROUP        ON CONELE.QRTZ_FIRED_TRIGGERS(JOB_GROUP) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_JOB_STATEFUL     ON CONELE.QRTZ_FIRED_TRIGGERS(IS_STATEFUL) TABLESPACE CONELE_IDX;
CREATE INDEX CONELE.IDX_QRTZ_FT_JOB_REQ_RECOVERY ON CONELE.QRTZ_FIRED_TRIGGERS(REQUESTS_RECOVERY) TABLESPACE CONELE_IDX;

GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_JOB_DETAILS         TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_JOB_LISTENERS       TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_TRIGGERS            TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_SIMPLE_TRIGGERS     TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_CRON_TRIGGERS       TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_BLOB_TRIGGERS       TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_TRIGGER_LISTENERS   TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_CALENDARS           TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_PAUSED_TRIGGER_GRPS TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_FIRED_TRIGGERS      TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_SCHEDULER_STATE     TO APP_CONELE;
GRANT DELETE,UPDATE,SELECT,INSERT ON CONELE.QRTZ_LOCKS               TO APP_CONELE;

INSERT INTO CONELE.QRTZ_LOCKS VALUES('TRIGGER_ACCESS');
INSERT INTO CONELE.QRTZ_LOCKS VALUES('JOB_ACCESS');
INSERT INTO CONELE.QRTZ_LOCKS VALUES('CALENDAR_ACCESS');
INSERT INTO CONELE.QRTZ_LOCKS VALUES('STATE_ACCESS');
INSERT INTO CONELE.QRTZ_LOCKS VALUES('MISFIRE_ACCESS');
COMMIT;

spool off
