spool 3_grants.log

GRANT SELECT ON IICE.TBL_EXPEDIENTE TO CONELE;
GRANT SELECT ON IICE.TBL_CLIENTE TO CONELE;
GRANT SELECT ON IICE.TBL_OFICINA TO CONELE;
GRANT SELECT ON IICE.TBL_EMPLEADO TO CONELE;

spool off
