spool 5_createTable.log

CREATE TABLE CONELE.TBL_CE_IBM_MULTITABLA (
  ID NUMBER(10,0) NOT NULL ENABLE, 
  ID_PARAMETRIA NUMBER(10,0), 
  TIPO NUMBER(10,0) NOT NULL ENABLE, 
  NOMBRE VARCHAR2(300 CHAR) NOT NULL ENABLE, 
  DESCRIPCION VARCHAR2(500 CHAR), 
  ESTADO CHAR(1 CHAR) DEFAULT 'A' NOT NULL ENABLE, 
  CODIGO VARCHAR2(50 BYTE), 
  CODIGO_ETI VARCHAR2(100 BYTE), 
  CODIGO_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  ENTERO NUMBER(10,0), 
  ENTERO_ETI VARCHAR2(100 CHAR), 
  ENTERO_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  DECIMALES NUMBER, 
  DECIMALES_ETI VARCHAR2(100 CHAR), 
  DECIMALES_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  TEXTO VARCHAR2(500 CHAR), 
  TEXTO_ETI VARCHAR2(100 CHAR), 
  TEXTO_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  FECHA DATE, 
  FECHA_ETI VARCHAR2(100 CHAR), 
  FECHA_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  HORA CHAR(5 CHAR), 
  HORA_ETI VARCHAR2(100 BYTE), 
  HORA_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  BOOLEANO CHAR(1 BYTE), 
  BOOLEANO_ETI VARCHAR2(100 CHAR), 
  BOOLEANO_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  FUNCION VARCHAR2(100 CHAR), 
  FUNCION_ETI VARCHAR2(100 BYTE), 
  FUNCION_HABIL CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
  FUNCION_MSG VARCHAR2(200 CHAR), 
  PERMITE_HIJO CHAR(1 BYTE), 
  FECHA_MODIFICA DATE, 
  FECHA_CREA DATE NOT NULL ENABLE, 
  USU_CREA CHAR(7 CHAR) NOT NULL ENABLE, 
  USU_MODIFICA CHAR(7 CHAR)
); 
ALTER TABLE CONELE.TBL_CE_IBM_MULTITABLA ADD CONSTRAINT PK_PARAMETRIA PRIMARY KEY (ID);
ALTER TABLE CONELE.TBL_CE_IBM_MULTITABLA ADD CONSTRAINT FK_PARAMETRIA_PARAMETRIA_1 FOREIGN KEY (ID_PARAMETRIA) REFERENCES CONELE.TBL_CE_IBM_MULTITABLA (ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_MULTITABLA TO APP_CONELE;

spool off
