spool 6_loadInitialData.log

INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(82, 1000, 'PB_HORA_JOB_GENERAR_ARCHIVO', '0 35 12 ? * * *');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(83, 1000, 'PB_HORA_JOB_DEPURAR_ARCHIVO', '0 35 13 ? * * *');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(84, 1000, 'PB_RUTA_ARCHIVO'            , '/mnt/compartido/conele/out');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(85, 1000, 'PB_NOMBRE_ARCHIVO'          , 'PACK');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(86, 1000, 'PB_FORMATO_FECHA_SUFIJO'    , 'yyyyMMddHHmm');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(87, 1000, 'PB_APAGAR_APLICACION_PLD'   , 'NO');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(88, 1000, 'PB_NRO_REGISTRO'            , '10');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(89, 1000, 'PB_DIAS_ESPERA'             , '1');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(90, 1000, 'PB_HOST_MAIL'               , 'smtp.gmail.com');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(91, 1000, 'PB_PORT_MAIL'               , '587');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(92, 1000, 'PB_USER_MAIL'               , 'juanquedena@gmail.com');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(93, 1000, 'PB_PASSWD_MAIL'             , 'jyq_198405');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(94, 1000, 'PB_LIST_SEND'               , 'juanquedena@gmail.com');
COMMIT;

spool off
