spool 6_loadInitialData.log

INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(82, 1000, 'PB_HORA_JOB_GENERAR_ARCHIVO', '0 35 12 ? * * *');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(83, 1000, 'PB_HORA_JOB_DEPURAR_ARCHIVO', '0 35 13 ? * * *');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(84, 1000, 'PB_RUTA_ARCHIVO'            , '/mnt/compartido/conele/out');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(85, 1000, 'PB_NOMBRE_ARCHIVO'          , 'PACK');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(86, 1000, 'PB_FORMATO_FECHA_SUFIJO'    , 'yyyyMMddHHmm');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(87, 1000, 'PB_APAGAR_APLICACION_PLD'   , 'NO');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF(ID, CODIGO_APLICATIVO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES(88, 1000, 'PB_NRO_REGISTRO'            , '10');
COMMIT;

spool off
