@07_loadInitialDataBatch.sql
@08_updateBlob_READER_XML_WSDL.sql
@09_updateBlob_READER_XML_RULE_TERRITORIO.sql
@10_updateBlob_READER_XML_RULE_OFICINA.sql
@11_updateBlob_RULE.sql
@12_updateBlob_DECISOR_PARAM.sql
@13_updateBlob_RULE_DECISOR_PARAM.sql
@14_updateBlob_RULE_PARAM.sql
@15_updateBlob_DepurarArchivo.sql
