package packws.cargaterritorio

import java.util.List;
import java.util.Map;
import java.util.HashMap;

import com.bbva.batch.domain.ItemBatch;

rule "100 Valida Oficina"
dialect "java" 
salience 100
no-loop true
when
    items: List() from collect(ItemBatch())
then
    String key;
    ItemBatch io;
    Map<String, String> keys = new HashMap<String, String>();
    
	for(Object o : items){
		io = (ItemBatch) o;
		io.setObject("__filter__", "0");
		if(io.existsKey("listaOficina.id")) {
		key = io.getString("listaOficina.id");
		  if(!keys.containsKey(key)) {
			  keys.put(key, key);
			  io.setObject("__filter__", "1");
          }
		}
	}
end