package packws.cargaterritorio

import java.util.List;
import java.util.Map;
import java.util.HashMap;

import com.bbva.batch.util.DeciderParam;

global java.util.Map status

rule "101 No Generar IICE"
dialect "java" 
salience 101
no-loop true
when
    param: DeciderParam(name == 'flagIICE', value == 'SI')
then
    org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(DeciderParam.class);
    logger.info("FAILED");
    status.put("status", "FAILED");
end